In [1]:
import matplotlib as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
indep = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep = dataset['charges']

In [ ]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3,random_state = 0)

In [ ]:
#from sklearn.preprocessing import StandardScaler
#sc=StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error', 'absolute_error', 'poisson'],
'max_features': ['sqrt','log2'],
'splitter':['best','random']}

In [9]:
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)

In [ ]:
#grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs= -1)

In [10]:
grid.fit(indep, dep)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [11]:
re=grid.cv_results_
grid_predictions = grid.predict(indep)
from sklearn.metrics import r2_score
r_score=r2_score(dep,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.
best_params_),r_score)

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'sqrt', 'splitter': 'best'}: 0.9921060428352511

In [12]:
 table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007767,0.000858,0.002845,0.000451,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.730512,0.592456,0.733078,0.597734,0.743694,0.679495,0.069074,4
1,0.004820,0.000875,0.003851,0.001040,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.685132,0.494439,0.673423,0.721332,0.640427,0.642951,0.078630,8
2,0.005651,0.000779,0.003610,0.002052,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.727226,0.630191,0.641865,0.722351,0.719508,0.688228,0.042852,2
3,0.004149,0.000284,0.002921,0.000792,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.754727,0.489047,0.661473,0.684722,0.672967,0.652587,0.087983,7
4,0.017698,0.001531,0.002702,0.001001,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.780508,0.636494,0.608546,0.727453,0.743516,0.699303,0.065610,1
5,0.016850,0.001887,0.002534,0.000433,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.743593,0.551160,0.574626,0.642686,0.642785,0.630970,0.067089,11
6,0.017226,0.001314,0.001847,0.000341,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.710289,0.656986,0.666507,0.571034,0.675286,0.656021,0.046152,6
7,0.014902,0.001549,0.002127,0.000271,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.611046,0.521644,0.712471,0.717094,0.608145,0.634080,0.073323,9
8,0.006015,0.001008,0.002413,0.000703,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.553166,0.669194,0.744062,0.758754,0.709267,0.686889,0.073660,3
9,0.004677,0.000751,0.002463,0.000640,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.699020,0.630970,0.662654,0.666219,0.680770,0.667927,0.022487,5
10,0.004806,0.001109,0.001955,0.000544,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.620312,0.665138,0.484834,0.722026,0.673750,0.633212,0.080911,10
11,0.004444,0.000852,0.002744,0.000773,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.608449,0.517782,0.661033,0.638139,0.696884,0.624457,0.060674,12

from sklearn.metrics import r2_score
table=pd.DataFrame.from_dict(re)
r_score=r2_score(y_test,grid_predictions)

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 34
BMI: 45
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 0

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[3410.324]

C:\Users\bkmad\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [16]:
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]