In [2]:
## declare the library and read the adta from the csv file
import pandas as pd
dataset=pd.read_csv("Salary_Data.csv")
dataset

    id  yearsofexperience  salary
0    1                  1   45000
1    2                  2   52000
2    3                  3   61000
3    4                  4   48000
4    5                  5   75000
5    6                  6   68000
6    7                  7   55000
7    8                  8   72000
8    9                  9   49000
9   10                 10   83000
10  11                 11   67000
11  12                 12   58000
12  13                 13   91000
13  14                 14   64000
14  15                 15   76000
15  16                 16   53000
16  17                 17   88000
17  18                 18   62000
18  19                 19   71000
19  20                 20   95000
20  21                 21   67000
21  22                 22   58000
22  23                 23   91000
23  24                 24   64000
24  25                 25   76000
25  26                 26   53000
26  27                 27   88000
27  28                 28   62000
28  29                 29   71000
29  30                 30   95000

In [ ]:
## after read the file data store indepent varaiable
indepent

In [3]:
##Read the spectific column value
indepent=dataset[["yearsofexperience"]]

In [4]:
##Read the spectific output column value
dependent=dataset[["salary"]]

In [5]:
dependent

    salary
0    45000
1    52000
2    61000
3    48000
4    75000
5    68000
6    55000
7    72000
8    49000
9    83000
10   67000
11   58000
12   91000
13   64000
14   76000
15   53000
16   88000
17   62000
18   71000
19   95000
20   67000
21   58000
22   91000
23   64000
24   76000
25   53000
26   88000
27   62000
28   71000
29   95000

In [6]:
##split the dta and declare the inpu and output varable  x is input variable and y is output variable
## sklearn .model used to split the input and output varaible
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(indepent, dependent, test_size=0.30)

In [7]:
X_train  #only input features input

    yearsofexperience
13                 14
14                 15
29                 30
9                  10
4                   5
21                 22
11                 12
27                 28
3                   4
7                   8
6                   7
26                 27
25                 26
12                 13
2                   3
15                 16
1                   2
16                 17
17                 18
0                   1
24                 25

In [8]:
 y_train  # only output values to train

    salary
13   64000
14   76000
29   95000
9    83000
4    75000
21   58000
11   58000
27   62000
3    48000
7    72000
6    55000
26   88000
25   53000
12   91000
2    61000
15   53000
1    52000
16   88000
17   62000
0    45000
24   76000

In [10]:
## sklearn.linear_model used to create the LinearRegression model   
# Learning phase
from sklearn.linear_model import LinearRegression
##regressor=LinearRegression()- non parameteris function
regressor=LinearRegression()
## fit used used to create AI brain model
regressor.fit(X_train,y_train)

LinearRegression()

In [11]:
regressor

LinearRegression()

In [12]:
#weight value  coef_ nothing thera is declare the value
weight=regressor.coef_
weight

array([[686.1952862]])

In [14]:
##bais term of your trained model
bais=regressor.intercept_
bais

array([57480.13468013])

In [26]:
y_pred=regressor.predict(X_test) X_test actual output is y_test

In [16]:

##measure how well your machine learning model performs if the score nearly by 1 good value or
##if the value nearl y by zero data is not perforly well

from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
print(score)

0.15750647150580155

In [17]:
y_pred

array([[73948.82154882],
       [71204.04040404],
       [70517.84511785],
       [71890.23569024],
       [77379.7979798 ],
       [61597.30639731],
       [73262.62626263],
       [63655.89225589],
       [65028.28282828]])

In [24]:
## create the  new file
import pickle
filename="finized_model_Linear.sav"

# dump the data into file
##dump the data into file
#pickle.dump(regressor, open('finized_model_Linear.sav', 'wb'))

In [25]:
pickle.dump(regressor, open(filename, 'wb'))

In [29]:
##load_model to use store the entire output value and rb used to read the value
load_model = pickle.load(open('finized_model_Linear.sav', 'rb')) 
# Predict using a 2D array (e.g., [[15]])
result = load_model.predict([[15]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [30]:
result

array([[67773.06397306]])